-- 운영과 분리된 일회용 DB에서 신규 migration SQL을 검증하기 위한 최소 prerequisite.
-- 운영 스키마를 그대로 복제하지 않는다. 신규 migration이 참조하는 객체만 만든다.
-- 컬럼 타입은 2026-07-30 운영 information_schema 조회 결과와 일치시킨다.

create extension if not exists pgcrypto;

-- Supabase 역할
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then create role anon nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then create role authenticated nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then create role service_role nologin bypassrls; end if;
end $$;

-- Supabase auth 스키마 최소 구성
create schema if not exists auth;

create table if not exists auth.users (
  id uuid primary key default gen_random_uuid()
);

create or replace function auth.uid() returns uuid language sql stable as $$ select null::uuid $$;
create or replace function auth.role() returns text language sql stable as $$ select 'anon'::text $$;

-- 게시판
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text,
  content text,
  status text default 'published'
);

-- 게임 데이터 (weapon_patch_editable_columns 대상 + 적용 RPC 캐스팅 검증용)
create table if not exists public.weapons (
  id text primary key,
  name text not null,
  type text not null,
  ammo text,
  availability text,
  spawn_maps text,
  damage integer,
  bullet_speed integer,
  patch_notes text,
  weight numeric,
  can_be_in_backpack boolean
);

create table if not exists public.attachments (
  id text primary key,
  name text not null,
  type text not null,
  weight numeric,
  patch_notes text,
  slot text,
  vertical_recoil integer,
  horizontal_recoil integer,
  reload_speed integer,
  ads_speed integer
);

create table if not exists public.ammo (
  id text primary key,
  name text not null,
  type text not null,
  weight numeric,
  patch_notes text
);

create table if not exists public.consumables (
  id text primary key,
  name text not null,
  type text not null,
  weight numeric,
  cast_time text,
  patch_notes text
);

create table if not exists public.throwables (
  id text primary key,
  name text not null,
  type text not null,
  weight numeric,
  patch_notes text
);

create table if not exists public.vehicles (
  id text primary key,
  name text not null,
  trunk_capacity integer not null,
  patch_notes text
);

-- 쓰기 정책 강화 대상 테이블 (정책 이름까지 운영과 동일하게 재현)
create table if not exists public.pubg_player_cache (
  id text primary key,
  lower_nickname text,
  platform text
);
alter table public.pubg_player_cache enable row level security;
create policy "Service Role Write" on public.pubg_player_cache for all using (true) with check (true);
create policy "Public Read" on public.pubg_player_cache for select using (true);

create table if not exists public.processed_match_telemetry (
  match_id text,
  platform text,
  player_id text,
  data jsonb
);
alter table public.processed_match_telemetry enable row level security;
create policy "Allow authenticated insert" on public.processed_match_telemetry
  for insert with check (auth.role() = 'authenticated');
create policy "Allow authenticated update" on public.processed_match_telemetry
  for update using (auth.role() = 'authenticated');
create policy "Allow public read-only access" on public.processed_match_telemetry
  for select using (true);

create table if not exists public.match_stats_raw (
  match_id text,
  data jsonb
);
alter table public.match_stats_raw enable row level security;
create policy "Allow authenticated insert only" on public.match_stats_raw
  for insert with check (auth.role() = 'authenticated');
create policy "Allow public read" on public.match_stats_raw for select using (true);

create table if not exists public.match_master_telemetry (match_id text, data jsonb);
create table if not exists public.global_benchmarks (id text primary key, value numeric);
create table if not exists public.sync_history (type text primary key, last_url text, updated_at timestamptz);

grant select, insert, update, delete on all tables in schema public to anon, authenticated, service_role;
