-- 운영과 분리된 일회용 DB에서 신규 migration SQL을 검증하기 위한 최소 prerequisite.
-- 운영 스키마를 그대로 복제하지 않는다. 신규 migration이 참조하는 객체만 만든다.
-- 컬럼 타입은 2026-07-30 운영 information_schema 조회 결과와 일치시킨다.

create extension if not exists pgcrypto;

-- Supabase 역할
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then create role anon nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then create role authenticated nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then create role service_role nologin bypassrls; end if;
end $$;

-- Supabase auth 스키마 최소 구성
create schema if not exists auth;

create table if not exists auth.users (
  id uuid primary key default gen_random_uuid()
);

create or replace function auth.uid() returns uuid language sql stable as $$ select null::uuid $$;
create or replace function auth.role() returns text language sql stable as $$ select 'anon'::text $$;

-- linked-player sync candidate source
create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  pubg_nickname text,
  pubg_platform text default 'steam',
  last_active_at timestamptz,
  updated_at timestamptz default now()
);
grant select on table public.profiles to anon, authenticated, service_role;

-- 게시판
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text,
  content text,
  status text default 'published'
);

-- 게임 데이터 (weapon_patch_editable_columns 대상 + 적용 RPC 캐스팅 검증용)
create table if not exists public.weapons (
  id text primary key,
  name text not null,
  type text not null,
  ammo text,
  availability text,
  spawn_maps text,
  damage integer,
  bullet_speed integer,
  patch_notes text,
  weight numeric,
  can_be_in_backpack boolean
);

create table if not exists public.attachments (
  id text primary key,
  name text not null,
  type text not null,
  weight numeric,
  patch_notes text,
  slot text,
  vertical_recoil integer,
  horizontal_recoil integer,
  reload_speed integer,
  ads_speed integer
);

create table if not exists public.ammo (
  id text primary key,
  name text not null,
  type text not null,
  weight numeric,
  patch_notes text
);

create table if not exists public.consumables (
  id text primary key,
  name text not null,
  type text not null,
  weight numeric,
  cast_time text,
  patch_notes text
);

create table if not exists public.throwables (
  id text primary key,
  name text not null,
  type text not null,
  weight numeric,
  patch_notes text
);

create table if not exists public.vehicles (
  id text primary key,
  name text not null,
  trunk_capacity integer not null,
  patch_notes text
);

-- 쓰기 정책 강화 대상 테이블 (정책 이름까지 운영과 동일하게 재현)
create table if not exists public.pubg_player_cache (
  id text primary key,
  lower_nickname text,
  platform text
);
alter table public.pubg_player_cache enable row level security;
create policy "Service Role Write" on public.pubg_player_cache for all using (true) with check (true);
create policy "Public Read" on public.pubg_player_cache for select using (true);

create table if not exists public.processed_match_telemetry (
  match_id text,
  platform text,
  player_id text,
  data jsonb
);
alter table public.processed_match_telemetry enable row level security;
create policy "Allow authenticated insert" on public.processed_match_telemetry
  for insert with check (auth.role() = 'authenticated');
create policy "Allow authenticated update" on public.processed_match_telemetry
  for update using (auth.role() = 'authenticated');
create policy "Allow public read-only access" on public.processed_match_telemetry
  for select using (true);

create table if not exists public.match_stats_raw (
  match_id text,
  data jsonb
);
alter table public.match_stats_raw enable row level security;
create policy "Allow authenticated insert only" on public.match_stats_raw
  for insert with check (auth.role() = 'authenticated');
create policy "Allow public read" on public.match_stats_raw for select using (true);

create table if not exists public.match_master_telemetry (match_id text, data jsonb);

-- Recovery-claim migration prerequisite. Keep the identity key and lease
-- columns faithful to the telemetry cache registry so the claim RPC can be
-- exercised without replaying the full historical telemetry migrations.
create table if not exists public.telemetry_map_cache_entries (
  id bigint generated by default as identity primary key,
  match_id text not null,
  platform text not null check (platform in ('steam', 'kakao')),
  player_id text not null,
  mode text not null check (mode in ('lite', 'full')),
  telemetry_version numeric not null,
  storage_path text not null unique,
  status text not null default 'pending' check (status in ('pending', 'ready')),
  lease_expires_at timestamptz,
  lease_token uuid,
  updated_at timestamptz not null default now(),
  unique (match_id, platform, player_id, mode, telemetry_version)
);

-- The recovery claim is SECURITY INVOKER and inserts without an explicit id;
-- grant only the sequence privilege needed by service_role for nextval().
grant usage on sequence public.telemetry_map_cache_entries_id_seq to service_role;

-- Existing benchmark population (the 202609 migration adds provenance to this
-- table and replaces the view below). Keep the production column order/types
-- needed by the view, partial index, and executable scenario.
create table if not exists public.global_benchmarks (
  id bigint generated by default as identity primary key,
  match_id text not null,
  player_id text not null,
  platform text not null default 'legacy_unknown',
  counter_latency_ms double precision,
  initiative_rate double precision,
  damage double precision,
  kills integer,
  survival_time integer,
  game_mode text,
  created_at timestamptz default now(),
  duel_win_rate double precision,
  trade_rate double precision,
  revive_rate double precision,
  smoke_rate double precision,
  pressure_index double precision,
  team_wipes integer default 0,
  reversal_rate double precision,
  isolation_index double precision,
  min_dist double precision,
  trade_latency_ms double precision,
  solo_kill_rate integer default 0,
  death_phase integer,
  tier text default 'A',
  match_type text default 'official',
  filter_version integer default 1
);

-- Existing weapon sample population and its two pre-provenance RPC overloads.
create table if not exists public.weapon_meta_match_samples (
  id bigint generated always as identity primary key,
  match_id text not null,
  platform text not null,
  player_id text not null,
  played_at timestamptz not null,
  patch_version text not null,
  weapon_category text not null,
  weapon_name text not null,
  active_pick boolean not null default false,
  total_kills integer not null default 0,
  total_dbnos integer not null default 0,
  total_damage numeric(12, 2) not null default 0,
  first_sec_hits integer,
  sustained_hits integer,
  sustained_burst_count integer,
  match_type text not null default 'unknown'
);

alter table public.weapon_meta_match_samples enable row level security;
grant all on table public.weapon_meta_match_samples to service_role;

create or replace view public.benchmark_stats_by_tier as
select
  b.tier,
  b.game_mode,
  b.match_type,
  count(*) as match_count,
  avg(nullif(b.damage, -1::double precision)) as avg_damage,
  avg(nullif(b.kills, -1)) as avg_kills,
  avg(nullif(b.survival_time, -1)) as avg_survival_time,
  avg(nullif(b.duel_win_rate, -1::double precision)) as avg_duel_win_rate,
  avg(nullif(b.initiative_rate, -1::double precision)) as avg_initiative_rate,
  avg(nullif(b.trade_rate, -1::double precision)) as avg_trade_rate,
  avg(nullif(b.revive_rate, -1::double precision)) as avg_revive_rate,
  avg(nullif(b.smoke_rate, -1::double precision)) as avg_smoke_rate,
  avg(nullif(b.pressure_index, -1::double precision)) as avg_pressure_index,
  avg(nullif(b.team_wipes, -1)) as avg_team_wipes,
  avg(nullif(b.reversal_rate, -1::double precision)) as avg_reversal_rate,
  avg(nullif(b.isolation_index, -1::double precision)) as avg_isolation_index,
  avg(nullif(b.min_dist, -1::double precision)) as avg_min_dist,
  avg(nullif(b.counter_latency_ms, -1::double precision)) as avg_counter_latency_ms,
  avg(nullif(b.trade_latency_ms, -1::double precision)) as avg_trade_latency_ms,
  avg(nullif(b.solo_kill_rate, -1)) as avg_solo_kill_rate,
  avg(nullif(b.death_phase, -1)) as avg_death_phase
from public.global_benchmarks as b
group by b.tier, b.game_mode, b.match_type;

create or replace function public.get_weapon_meta_comparison(
  p_patch_version text,
  p_patch_started_at timestamptz,
  p_baseline_days integer default 14
)
returns table (
  weapon_name text,
  weapon_category text,
  period text,
  player_match_count bigint,
  active_pick_count bigint,
  total_damage numeric,
  total_kills bigint,
  total_dbnos bigint,
  first_sec_hits bigint,
  sustained_hits bigint,
  sustained_burst_count bigint,
  burst_sample_count bigint
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    s.weapon_name,
    max(s.weapon_category),
    'pre'::text,
    count(distinct (s.match_id, s.platform, s.player_id)),
    count(*) filter (where s.active_pick),
    coalesce(sum(s.total_damage) filter (where s.active_pick), 0),
    coalesce(sum(s.total_kills) filter (where s.active_pick), 0),
    coalesce(sum(s.total_dbnos) filter (where s.active_pick), 0),
    coalesce(sum(s.first_sec_hits), 0),
    coalesce(sum(s.sustained_hits), 0),
    coalesce(sum(s.sustained_burst_count), 0),
    count(*) filter (where s.sustained_hits is not null)
  from public.weapon_meta_match_samples as s
  where false
  group by s.weapon_name;
$$;

create or replace function public.get_weapon_meta_comparison(
  p_patch_version text,
  p_patch_started_at timestamptz,
  p_baseline_days integer,
  p_match_type text
)
returns table (
  weapon_name text,
  weapon_category text,
  period text,
  player_match_count bigint,
  active_pick_count bigint,
  total_damage numeric,
  total_kills bigint,
  total_dbnos bigint,
  first_sec_hits bigint,
  sustained_hits bigint,
  sustained_burst_count bigint,
  burst_sample_count bigint
)
language sql
stable
security invoker
set search_path = public
as $$
  select *
  from public.get_weapon_meta_comparison(p_patch_version, p_patch_started_at, p_baseline_days);
$$;

create table if not exists public.sync_history (type text primary key, last_url text, updated_at timestamptz);

grant select, insert, update, delete on all tables in schema public to anon, authenticated, service_role;
