-- Community agent migration verification runs only in a disposable local PostgreSQL.
-- These are the minimum existing BGMS objects required by the real board writer.
create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then create role anon nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then create role authenticated nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then create role service_role nologin bypassrls; end if;
end $$;

create schema if not exists auth;
create schema if not exists storage;

create table auth.users (id uuid primary key default gen_random_uuid());
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  role text not null default 'user'
);
create table public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  content text not null,
  category text not null,
  image_url text,
  is_notice boolean not null default false,
  author text not null,
  user_id uuid,
  password_hash text,
  ip_address text,
  discord_url text,
  discord_channel_id text,
  clan_info jsonb,
  status text not null default 'published',
  revision bigint not null default 0
);
create table public.agent_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  status text not null default 'running' check (status in ('running', 'completed', 'failed')),
  message text not null,
  system_prompt text,
  summary text,
  error text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);
create table public.sync_history (
  id uuid primary key default gen_random_uuid(),
  type text not null unique,
  last_url text,
  updated_at timestamptz not null default now()
);

create table storage.buckets (
  id text primary key,
  name text not null,
  public boolean not null default false,
  file_size_limit bigint,
  allowed_mime_types text[]
);
create table storage.objects (
  id uuid primary key default gen_random_uuid(),
  bucket_id text not null references storage.buckets(id),
  name text not null,
  owner uuid,
  metadata jsonb,
  unique (bucket_id, name)
);

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.agent_runs enable row level security;
alter table public.sync_history enable row level security;
alter table storage.objects enable row level security;

grant usage on schema public, auth, storage to service_role, anon, authenticated;
grant select, insert, update, delete on all tables in schema public to service_role;
grant select, insert, update, delete on table auth.users, storage.objects to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into storage.buckets (id, name, public) values ('images', 'images', true);
