create table public.comments(id bigint generated by default as identity primary key,post_id bigint not null references public.posts(id),user_id uuid,author text not null,content text not null,parent_id bigint references public.comments(id),created_at timestamptz not null default now(),password_hash text,ip_address text);
create table public.notifications(id bigint generated by default as identity primary key,user_id uuid,sender_id uuid,sender_name text,type text,post_id bigint,preview_text text);
grant select,insert,update,delete on public.comments,public.notifications to service_role;
grant usage,select on all sequences in schema public to service_role;
insert into auth.users(id) values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');
insert into public.profiles(id,nickname,role) values('11111111-1111-4111-8111-111111111111','BGMS AI 비서','user'),('22222222-2222-4222-8222-222222222222','review admin','admin');
update public.community_agent_policy set bot_user_id='11111111-1111-4111-8111-111111111111',enabled=true;
