"use client";

import { useEffect, useState } from "react";
import { toast } from "sonner";

type Faq = { id?: string; category: string; question: string; answer: string; sort_order: number; is_published: boolean };
const EMPTY: Faq = { category: "stats", question: "", answer: "", sort_order: 0, is_published: true };

export default function SupportFaqEditor() {
  const [faqs, setFaqs] = useState<Faq[]>([]);
  const [draft, setDraft] = useState<Faq>(EMPTY);
  const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { const response = await fetch("/api/admin/support/faqs"); const data = await response.json(); if (!response.ok) throw new Error(); setFaqs(Array.isArray(data.faqs) ? data.faqs : []); } catch { toast.error("FAQ를 불러오지 못했습니다."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function save() { try { const response = await fetch("/api/admin/support/faqs", { method: draft.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...draft, sortOrder: draft.sort_order, isPublished: draft.is_published }) }); if (!response.ok) throw new Error(); setDraft(EMPTY); await load(); toast.success("FAQ를 저장했습니다."); } catch { toast.error("FAQ를 저장하지 못했습니다."); } }
  return <section aria-label="FAQ 관리" className="rounded-2xl border border-white/10 bg-[#151515] p-5 text-white"><div className="flex items-center justify-between"><h2 className="text-lg font-black">FAQ 관리</h2><button type="button" onClick={() => setDraft(EMPTY)} className="text-xs text-white/60">새 FAQ</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-white/60">카테고리<select aria-label="FAQ 카테고리" value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })} className="mt-1 min-h-10 w-full rounded-lg border border-white/10 bg-black/20 px-2 text-sm"><option value="stats">전적</option><option value="account">계정</option><option value="community">커뮤니티</option><option value="feature">기능</option></select></label><label className="text-xs font-bold text-white/60">정렬 순서<input aria-label="FAQ 정렬 순서" type="number" value={draft.sort_order} onChange={(event) => setDraft({ ...draft, sort_order: Number(event.target.value) })} className="mt-1 min-h-10 w-full rounded-lg border border-white/10 bg-black/20 px-2 text-sm" /></label><label className="text-xs font-bold text-white/60 sm:col-span-2">질문<input aria-label="FAQ 질문" value={draft.question} onChange={(event) => setDraft({ ...draft, question: event.target.value })} className="mt-1 min-h-10 w-full rounded-lg border border-white/10 bg-black/20 px-2 text-sm" /></label><label className="text-xs font-bold text-white/60 sm:col-span-2">답변<textarea aria-label="FAQ 답변" value={draft.answer} onChange={(event) => setDraft({ ...draft, answer: event.target.value })} rows={4} className="mt-1 w-full rounded-lg border border-white/10 bg-black/20 p-2 text-sm" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.is_published} onChange={(event) => setDraft({ ...draft, is_published: event.target.checked })} />게시 중</label></div><button type="button" onClick={() => void save()} disabled={!draft.question.trim() || !draft.answer.trim()} className="mt-4 min-h-10 rounded-lg bg-amber-400 px-4 text-sm font-black text-black disabled:opacity-40">FAQ 저장</button>{!loading && <div className="mt-5 space-y-2">{faqs.map((faq) => <button key={faq.id} type="button" onClick={() => setDraft(faq)} className="block w-full rounded-lg border border-white/10 p-3 text-left text-sm hover:border-white/25"><span className="font-bold">{faq.question}</span><span className="ml-2 text-xs text-white/45">{faq.is_published ? "게시" : "숨김"}</span></button>)}</div>}</section>;
}
