-- 개인 제재 관찰 목록과 서버 전용 PUBG 상태 캐시.
-- 모든 입력은 서버에서 검증하며 service_role만 새 객체에 접근한다.

create table public.pubg_ban_watch_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  platform text not null check (platform in ('steam', 'kakao')),
  subject_account_id text not null check (subject_account_id ~ '^account\.[A-Za-z0-9_-]+$'),
  target_account_id text not null check (target_account_id ~ '^account\.[A-Za-z0-9_-]+$'),
  match_id text not null check (match_id ~ '^[A-Za-z0-9._-]{1,160}$'),
  event_at timestamptz not null,
  role text not null check (role in ('killer', 'finisher', 'knocker')),
  nickname_at_match text not null check (char_length(btrim(nickname_at_match)) between 1 and 64),
  map_name text check (map_name is null or char_length(map_name) <= 128),
  weapon text check (weapon is null or char_length(weapon) <= 128),
  note text check (note is null or char_length(note) <= 200),
  created_at timestamptz not null default now(),
  active_until timestamptz not null default (now() + interval '30 days'),
  baseline_status text check (baseline_status is null or baseline_status in ('none', 'temporary', 'permanent', 'unknown')),
  baseline_checked_at timestamptz,
  last_viewed_at timestamptz,
  unique (user_id, platform, subject_account_id, target_account_id, match_id, event_at, role)
);

create index pubg_ban_watch_items_user_created_idx
  on public.pubg_ban_watch_items (user_id, created_at desc);
create index pubg_ban_watch_items_user_active_target_idx
  on public.pubg_ban_watch_items (user_id, target_account_id, active_until);

create table public.pubg_ban_status (
  platform text not null check (platform in ('steam', 'kakao')),
  account_id text not null check (account_id ~ '^account\.[A-Za-z0-9_-]+$'),
  raw_ban_type text,
  normalized_status text not null default 'unknown' check (normalized_status in ('none', 'temporary', 'permanent', 'unknown')),
  checked_at timestamptz,
  last_attempt_at timestamptz,
  last_error text,
  next_check_at timestamptz,
  lease_token uuid,
  lease_expires_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (platform, account_id)
);

create index pubg_ban_status_next_check_idx
  on public.pubg_ban_status (next_check_at nulls first, platform, account_id);

create table public.pubg_ban_status_events (
  id bigint generated by default as identity primary key,
  platform text not null check (platform in ('steam', 'kakao')),
  account_id text not null check (account_id ~ '^account\.[A-Za-z0-9_-]+$'),
  previous_status text check (previous_status is null or previous_status in ('none', 'temporary', 'permanent', 'unknown')),
  observed_status text not null check (observed_status in ('none', 'temporary', 'permanent', 'unknown')),
  raw_ban_type text,
  observed_at timestamptz not null,
  observation_id uuid not null default gen_random_uuid(),
  unique (observation_id)
);

create index pubg_ban_status_events_account_observed_idx
  on public.pubg_ban_status_events (platform, account_id, observed_at desc);

alter table public.pubg_ban_watch_items enable row level security;
alter table public.pubg_ban_status enable row level security;
alter table public.pubg_ban_status_events enable row level security;

revoke all on table public.pubg_ban_watch_items from public, anon, authenticated;
revoke all on table public.pubg_ban_status from public, anon, authenticated;
revoke all on table public.pubg_ban_status_events from public, anon, authenticated;
grant all on table public.pubg_ban_watch_items to service_role;
grant all on table public.pubg_ban_status to service_role;
grant all on table public.pubg_ban_status_events to service_role;
grant usage, select on sequence public.pubg_ban_status_events_id_seq to service_role;

create or replace function public.create_pubg_ban_watch_item(
  p_user_id uuid,
  p_platform text,
  p_subject_account_id text,
  p_target_account_id text,
  p_match_id text,
  p_event_at timestamptz,
  p_role text,
  p_nickname_at_match text,
  p_map_name text default null,
  p_weapon text default null,
  p_note text default null,
  p_baseline_status text default null,
  p_baseline_checked_at timestamptz default null,
  p_active_until timestamptz default null
)
returns jsonb
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
declare
  v_existing public.pubg_ban_watch_items%rowtype;
  v_user_target_count integer;
  v_target_match_count integer;
  v_has_target boolean;
  v_has_match boolean;
  v_active_until timestamptz := coalesce(p_active_until, now() + interval '30 days');
begin
  if p_user_id is null
    or p_platform not in ('steam', 'kakao')
    or p_subject_account_id is null or p_subject_account_id !~ '^account\.[A-Za-z0-9_-]+$'
    or p_target_account_id is null or p_target_account_id !~ '^account\.[A-Za-z0-9_-]+$'
    or p_match_id is null or p_match_id !~ '^[A-Za-z0-9._-]{1,160}$'
    or p_event_at is null
    or p_role not in ('killer', 'finisher', 'knocker')
    or p_nickname_at_match is null or char_length(btrim(p_nickname_at_match)) not between 1 and 64
    or p_map_name is not null and char_length(p_map_name) > 128
    or p_weapon is not null and char_length(p_weapon) > 128
    or p_note is not null and char_length(p_note) > 200
    or p_baseline_status is not null and p_baseline_status not in ('none', 'temporary', 'permanent', 'unknown')
    or v_active_until <= now() then
    return jsonb_build_object('code', 'invalid_input');
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  select * into v_existing
  from public.pubg_ban_watch_items as item
  where item.user_id = p_user_id
    and item.platform = p_platform
    and item.subject_account_id = p_subject_account_id
    and item.target_account_id = p_target_account_id
    and item.match_id = p_match_id
    and item.event_at = p_event_at
    and item.role = p_role;
  if found then
    return jsonb_build_object('code', 'duplicate', 'id', v_existing.id);
  end if;

  select exists (
    select 1 from public.pubg_ban_watch_items as item
    where item.user_id = p_user_id
      and item.platform = p_platform
      and item.target_account_id = p_target_account_id
      and item.active_until > now()
  ) into v_has_target;
  if not v_has_target then
    select count(distinct item.platform || ':' || item.target_account_id)::integer into v_user_target_count
    from public.pubg_ban_watch_items as item
    where item.user_id = p_user_id and item.active_until > now();
    if v_user_target_count >= 50 then
      return jsonb_build_object('code', 'user_target_limit');
    end if;
  end if;

  select exists (
    select 1 from public.pubg_ban_watch_items as item
    where item.user_id = p_user_id
      and item.platform = p_platform
      and item.target_account_id = p_target_account_id
      and item.match_id = p_match_id
      and item.active_until > now()
  ) into v_has_match;
  if not v_has_match then
    select count(distinct item.match_id)::integer into v_target_match_count
    from public.pubg_ban_watch_items as item
    where item.user_id = p_user_id
      and item.platform = p_platform
      and item.target_account_id = p_target_account_id
      and item.active_until > now();
    if v_target_match_count >= 10 then
      return jsonb_build_object('code', 'target_match_limit');
    end if;
  end if;

  insert into public.pubg_ban_watch_items (
    user_id, platform, subject_account_id, target_account_id, match_id,
    event_at, role, nickname_at_match, map_name, weapon, note,
    active_until, baseline_status, baseline_checked_at
  ) values (
    p_user_id, p_platform, p_subject_account_id, p_target_account_id, p_match_id,
    p_event_at, p_role, btrim(p_nickname_at_match), nullif(btrim(p_map_name), ''),
    nullif(btrim(p_weapon), ''), nullif(p_note, ''), v_active_until,
    p_baseline_status, p_baseline_checked_at
  ) returning * into v_existing;

  return jsonb_build_object('code', 'created', 'id', v_existing.id);
end;
$function$;

create or replace function public.schedule_pubg_ban_status(
  p_platform text,
  p_account_id text,
  p_next_check_at timestamptz default null
)
returns boolean
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
begin
  if p_platform not in ('steam', 'kakao')
    or p_account_id is null or p_account_id !~ '^account\.[A-Za-z0-9_-]+$' then
    return false;
  end if;
  insert into public.pubg_ban_status (platform, account_id, next_check_at)
  values (p_platform, p_account_id, coalesce(p_next_check_at, now()))
  on conflict (platform, account_id) do update
    -- Scheduling is allowed to move a check earlier. This makes the user's
    -- explicit refresh useful while repeated registrations remain idempotent.
    set next_check_at = least(
      coalesce(public.pubg_ban_status.next_check_at, excluded.next_check_at),
      excluded.next_check_at
    ),
    updated_at = now();
  return true;
end;
$function$;

create or replace function public.claim_pubg_ban_status_batch(
  p_limit integer,
  p_lease_token uuid,
  p_lease_expires_at timestamptz
)
returns table (platform text, account_id text, lease_token uuid, lease_expires_at timestamptz)
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
begin
  if p_limit is null or p_limit < 1 or p_limit > 10
    or p_lease_token is null or p_lease_expires_at is null or p_lease_expires_at <= now() then
    return;
  end if;
  return query
  with due as (
    select status.platform, status.account_id
    from public.pubg_ban_status as status
    where (status.next_check_at is null or status.next_check_at <= now())
      and (status.lease_expires_at is null or status.lease_expires_at <= now())
      and exists (
        select 1 from public.pubg_ban_watch_items as item
        where item.platform = status.platform
          and item.target_account_id = status.account_id
          and item.active_until > now()
      )
    order by status.next_check_at nulls first, status.updated_at, status.platform, status.account_id
    limit least(p_limit, 10)
    for update skip locked
  )
  update public.pubg_ban_status as status
  set lease_token = p_lease_token,
      lease_expires_at = p_lease_expires_at,
      last_attempt_at = now(),
      updated_at = now()
  from due
  where status.platform = due.platform and status.account_id = due.account_id
  returning status.platform, status.account_id, status.lease_token, status.lease_expires_at;
end;
$function$;

create or replace function public.record_pubg_ban_observation(
  p_platform text,
  p_account_id text,
  p_raw_ban_type text,
  p_normalized_status text,
  p_checked_at timestamptz,
  p_next_check_at timestamptz,
  p_observation_id uuid default null,
  p_lease_token uuid default null
)
returns jsonb
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
declare
  v_previous text;
  v_observation uuid := coalesce(p_observation_id, gen_random_uuid());
  v_updated integer;
begin
  if p_platform not in ('steam', 'kakao')
    or p_account_id is null or p_account_id !~ '^account\.[A-Za-z0-9_-]+$'
    or p_normalized_status not in ('none', 'temporary', 'permanent', 'unknown')
    or p_checked_at is null or p_next_check_at is null then
    return jsonb_build_object('code', 'invalid_input');
  end if;

  insert into public.pubg_ban_status (platform, account_id, next_check_at)
  values (p_platform, p_account_id, p_next_check_at)
  on conflict (platform, account_id) do nothing;

  select case when checked_at is null then null else normalized_status end into v_previous
  from public.pubg_ban_status
  where platform = p_platform and account_id = p_account_id
  for update;

  insert into public.pubg_ban_status (
    platform, account_id, raw_ban_type, normalized_status, checked_at,
    last_attempt_at, last_error, next_check_at, lease_token, lease_expires_at
  ) values (
    p_platform, p_account_id, p_raw_ban_type, p_normalized_status, p_checked_at,
    now(), null, p_next_check_at, null, null
  )
  on conflict (platform, account_id) do update
    set raw_ban_type = excluded.raw_ban_type,
        normalized_status = excluded.normalized_status,
        checked_at = excluded.checked_at,
        last_attempt_at = excluded.last_attempt_at,
        last_error = null,
        next_check_at = excluded.next_check_at,
        lease_token = null,
        lease_expires_at = null,
        updated_at = now()
  where (p_lease_token is null or (
      public.pubg_ban_status.lease_token = p_lease_token
      and public.pubg_ban_status.lease_expires_at > now()
    ))
    and (public.pubg_ban_status.checked_at is null or excluded.checked_at >= public.pubg_ban_status.checked_at);
  get diagnostics v_updated = row_count;
  if v_updated <> 1 then
    return jsonb_build_object('code', 'stale');
  end if;

  if v_previous is null or v_previous is distinct from p_normalized_status then
    insert into public.pubg_ban_status_events (
      platform, account_id, previous_status, observed_status, raw_ban_type, observed_at, observation_id
    ) values (
      p_platform, p_account_id, v_previous, p_normalized_status, p_raw_ban_type, p_checked_at, v_observation
    ) on conflict (observation_id) do nothing;
  end if;

  return jsonb_build_object('code', 'recorded', 'observation_id', v_observation);
end;
$function$;

create or replace function public.extend_pubg_ban_watch_item(
  p_user_id uuid,
  p_item_id uuid,
  p_active_until timestamptz
)
returns jsonb
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
declare
  v_item public.pubg_ban_watch_items%rowtype;
  v_other_target boolean;
  v_same_match_active boolean;
  v_target_count integer;
begin
  if p_user_id is null or p_item_id is null or p_active_until is null or p_active_until <= now() then
    return jsonb_build_object('code', 'invalid_input');
  end if;
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));
  select * into v_item
  from public.pubg_ban_watch_items
  where id = p_item_id and user_id = p_user_id
  for update;
  if not found then return jsonb_build_object('code', 'not_found'); end if;
  select exists (
    select 1 from public.pubg_ban_watch_items as item
    where item.user_id = p_user_id and item.platform = v_item.platform
      and item.target_account_id = v_item.target_account_id
      and item.active_until > now() and item.id <> v_item.id
  ) into v_other_target;
  select exists (
    select 1 from public.pubg_ban_watch_items as item
    where item.user_id = p_user_id and item.platform = v_item.platform
      and item.target_account_id = v_item.target_account_id
      and item.match_id = v_item.match_id and item.active_until > now()
      and item.id <> v_item.id
  ) into v_same_match_active;
  if v_item.active_until <= now() and not v_other_target then
    select count(distinct item.platform || ':' || item.target_account_id)::integer into v_target_count
    from public.pubg_ban_watch_items as item
    where item.user_id = p_user_id and item.active_until > now();
    if v_target_count >= 50 then return jsonb_build_object('code', 'user_target_limit'); end if;
  end if;
  if v_item.active_until <= now() and not v_same_match_active then
    select count(distinct item.match_id)::integer into v_target_count
    from public.pubg_ban_watch_items as item
    where item.user_id = p_user_id and item.platform = v_item.platform
      and item.target_account_id = v_item.target_account_id and item.active_until > now();
    if v_target_count >= 10 then return jsonb_build_object('code', 'target_match_limit'); end if;
  end if;
  update public.pubg_ban_watch_items
  set active_until = greatest(v_item.active_until, p_active_until)
  where id = v_item.id and user_id = p_user_id;
  return jsonb_build_object('code', 'extended', 'id', v_item.id);
end;
$function$;

create or replace function public.record_pubg_ban_error(
  p_platform text,
  p_account_id text,
  p_error text,
  p_next_check_at timestamptz,
  p_lease_token uuid default null
)
returns boolean
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
declare
  v_updated integer;
begin
  if p_platform not in ('steam', 'kakao')
    or p_account_id is null or p_account_id !~ '^account\.[A-Za-z0-9_-]+$'
    or p_next_check_at is null then
    return false;
  end if;
  update public.pubg_ban_status
  set last_attempt_at = now(),
      last_error = left(nullif(btrim(p_error), ''), 200),
      next_check_at = p_next_check_at,
      lease_token = null,
      lease_expires_at = null,
      updated_at = now()
  where platform = p_platform and account_id = p_account_id
    and (p_lease_token is null or (
      lease_token = p_lease_token
      and lease_expires_at > now()
    ));
  get diagnostics v_updated = row_count;
  return v_updated = 1;
end;
$function$;

revoke all on function public.create_pubg_ban_watch_item(uuid, text, text, text, text, timestamptz, text, text, text, text, text, text, timestamptz, timestamptz) from public, anon, authenticated;
revoke all on function public.schedule_pubg_ban_status(text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.claim_pubg_ban_status_batch(integer, uuid, timestamptz) from public, anon, authenticated;
revoke all on function public.record_pubg_ban_observation(text, text, text, text, timestamptz, timestamptz, uuid, uuid) from public, anon, authenticated;
revoke all on function public.extend_pubg_ban_watch_item(uuid, uuid, timestamptz) from public, anon, authenticated;
revoke all on function public.record_pubg_ban_error(text, text, text, timestamptz, uuid) from public, anon, authenticated;
grant execute on function public.create_pubg_ban_watch_item(uuid, text, text, text, text, timestamptz, text, text, text, text, text, text, timestamptz, timestamptz) to service_role;
grant execute on function public.schedule_pubg_ban_status(text, text, timestamptz) to service_role;
grant execute on function public.claim_pubg_ban_status_batch(integer, uuid, timestamptz) to service_role;
grant execute on function public.record_pubg_ban_observation(text, text, text, text, timestamptz, timestamptz, uuid, uuid) to service_role;
grant execute on function public.extend_pubg_ban_watch_item(uuid, uuid, timestamptz) to service_role;
grant execute on function public.record_pubg_ban_error(text, text, text, timestamptz, uuid) to service_role;
